#!/bin/bash

# Update all Submodules to latest commit
cd $DESIGN_ROOT; git submodule foreach --recursive git pull
# for d in $DESIGN_ROOT/* ; do
#     if [ -f "$d/.git" ]; then
#         echo "Git Pulling $d"
#         cd $d; git pull; cd ..
#     fi
# done