// VGEN START: Autogenerated by /Users/davidmapstone/Documents/SoCLabs/RTL/accelerator-system-top/CHIPKIT/tools/vgen/bin/vgen.py on 10:59:11 24/03/2023

#ifndef CREGS_H 
#define CREGS_H 


typedef struct
{
	__IO uint32_t ACCELERATOR_EN;		/* Offset: 0x0 (R/W) Accelerator Enable Register */
	__IO uint32_t ACCELERATOR_CHANNEL_EN;		/* Offset: 0x4 (R/W) Accelerator Channel Enable Register */
} CREGS_TypeDef;

#endif

// VGEN END: Autogenerated by /Users/davidmapstone/Documents/SoCLabs/RTL/accelerator-system-top/CHIPKIT/tools/vgen/bin/vgen.py on 10:59:11 24/03/2023

