# // VGEN START: Autogenerated by /Users/davidmapstone/Documents/SoCLabs/RTL/accelerator-system-top/CHIPKIT/tools/vgen/bin/vgen.py on 10:59:11 24/03/2023

class Cregs(object):

	def __init__(self,base_offset):
		self.base_offset = base_offset


		self.ACCELERATOR_EN = self.base_offset + 0x0		# Accelerator Enable Register
		self.ACCELERATOR_CHANNEL_EN = self.base_offset + 0x4		# Accelerator Channel Enable Register
		self.ACCELERATOR_CHANNEL_EN = self.base_offset + 0x4		# Accelerator Channel Enable Register


# // VGEN END: Autogenerated by /Users/davidmapstone/Documents/SoCLabs/RTL/accelerator-system-top/CHIPKIT/tools/vgen/bin/vgen.py on 10:59:11 24/03/2023

