// VGEN END: Autogenerated by /Users/davidmapstone/Documents/SoCLabs/RTL/accelerator-system-top/CHIPKIT/tools/vgen/bin/vgen.py on 10:59:11 24/03/2023

#include "cregs_test.h"

// This test is intended to check initial (reset) values of registers
int cregs_initial_value_test(void) {
	int num_errors=0;

	if (SM2_CREGS->ACCELERATOR_EN != 0)		{num_errors += 1; puts("ERROR: ACCELERATOR_EN");}
	if (SM2_CREGS->ACCELERATOR_CHANNEL_EN != 0)		{num_errors += 1; puts("ERROR: ACCELERATOR_CHANNEL_EN");}


	return num_errors;

}

// This test is intended to check write read to registers
int cregs_write_read_test(void) {
	int num_errors=0;

	SM2_CREGS->ACCELERATOR_EN = 0xFFFFFFFF;	// write all-1s
	if (SM2_CREGS->ACCELERATOR_EN != (0xFFFFFFFF >> (32-32)))		{num_errors += 1; puts("ERROR: ACCELERATOR_EN");}	// check field is all-1s
	SM2_CREGS->ACCELERATOR_EN = 0x0;	// clear field
	if (SM2_CREGS->ACCELERATOR_EN != 0x0)		{num_errors += 1; puts("ERROR: ACCELERATOR_EN");}	// check field is all-0s
	SM2_CREGS->ACCELERATOR_CHANNEL_EN = 0xFFFFFFFF;	// write all-1s
	if (SM2_CREGS->ACCELERATOR_CHANNEL_EN != (0xFFFFFFFF >> (32-32)))		{num_errors += 1; puts("ERROR: ACCELERATOR_CHANNEL_EN");}	// check field is all-1s
	SM2_CREGS->ACCELERATOR_CHANNEL_EN = 0x0;	// clear field
	if (SM2_CREGS->ACCELERATOR_CHANNEL_EN != 0x0)		{num_errors += 1; puts("ERROR: ACCELERATOR_CHANNEL_EN");}	// check field is all-0s


	return num_errors;

}

// VGEN END: Autogenerated by /Users/davidmapstone/Documents/SoCLabs/RTL/accelerator-system-top/CHIPKIT/tools/vgen/bin/vgen.py on 10:59:11 24/03/2023

