// VGEN START: Autogenerated by /Users/davidmapstone/Documents/SoCLabs/RTL/accelerator-system-top/CHIPKIT/tools/vgen/bin/vgen.py on 10:59:11 24/03/2023

#ifndef CREGS_TEST_H 
#define CREGS_TEST_H 


#include "SM2_CM0.h"

// This test is intended to check initial (reset) values of registers
int cregs_initial_value_test(void);

// This test is intended to check write and read to registers
int cregs_write_read_test(void);

#endif

// VGEN END: Autogenerated by /Users/davidmapstone/Documents/SoCLabs/RTL/accelerator-system-top/CHIPKIT/tools/vgen/bin/vgen.py on 10:59:11 24/03/2023

